### ISSUE TITLE
quick question about live streams

### ISSUE THREAD

**Issue by victusfate** [bitmovin/bitcodin-node#1]
The bitcodin-python sample code includes [live streaming](https://github.com/bitmovin/bitcodin-python/blob/master/examples/create_live_stream.py). How would I go about configuring live streaming servers with the node module?

I'm looking at the rest api docs [here](http://docs.bitcodinrestapi.apiary.io/#reference/live-streaming/live-stream/create-a-live-stream?console=1) for how to proceed.

**Comment by moser4035** [comment]
Hi,
We have released version 0.2.1,
There you find an example for creating a live stream.

For live streaming, there is also a  blog post [here](https://www.bitcodin.com/blog/2015/11/mpeg-dash-and-hls-live-streaming-with-bitcodin) you can refer to.

Please let me know if everything works as expected.

Best regards,
David

**Comment by victusfate** [comment]
Sounds good, I wrote a little request wrapper which did the same but am happy to use the library.
You can close this one out, thanks for the rapid response!
