### ISSUE TITLE
s3 and google cloud storage content types for HLS output

### ISSUE THREAD

**Issue by victusfate** [bitmovin/bitcodin-node#2]
I've reached out via the sites interactive help, but thought maybe a ticket is a better place. This has more to do with the server side object creation but during live streaming the streams appear to play back in VLC (for the most part, some pausing), but not within mobile safari, or AVPlayer. As far as I can tell the only thing stopping them from playing back is setting the content-type properly for the master playlist/m3u8 and the various bitrate m3u8s to either application/vnd.apple.mpegurl or application/x-mpegURL

**Comment by victusfate** [comment]
oh heads up, stream played back in the app aok (some ios 9 changes to test code held me up). Mobile play would be nice but not a hold up.
Just need to create a new vod manifest on completion and we're in great shape. Thanks again for taking a look

**Comment by moser4035** [comment]
Hi, nice to hear it worked
thanks for letting us know.

A service for creating vod manifests for livestreams is on our roadmap and will be added in a future release.

Best regards,
David
